openapi: 3.0.1
info:
  title: 'OpenApiSample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  '/WeatherForecast':
    get:
      tags:
        - WeatherForecast
      summary: Get Weather Data
      description: Weather related data description
      operationId: GetWeatherForecast
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewWeatherForecast'
        '400':
          description: Bad Request
        '500':
          description: Server Error
        '503':
          description: Server Error
  '/WeatherForecast/{id}/':
    get:
      tags:
        - WeatherForecast
      summary: Get Weather Data by Id
      description: Weather related data description
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewWeatherForecast'
        '400':
          description: Bad Request
        '500':
          description: Server Error
        '503':
          description: Server Error
components:
  schemas:
    NewWeatherForecast:
      type: object
      properties:
        newDate:
          type: string
          format: date
        temperatureC:
          type: integer
          format: int32
        temperatureF:
          type: integer
          format: int32
          readOnly: true
        newSummary:
          type: string
          nullable: true
      additionalProperties: false